version: '3.7'
services:
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - ./db/mysql_init:/docker-entrypoint-initdb.d
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_USER: keystone
            MYSQL_PASSWORD: keystone_passsword
        networks:
            app_net:
                ipv4_address: 10.30.0.10

    memcached:
        image: memcached
        networks:
            app_net:
                ipv4_address: 10.30.0.11

    rabbitmq:
        image: rabbitmq:3.7-rc-alpine
        ports:  
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq-data:/var/lib/rabbitmq
        networks:
            app_net:
                ipv4_address: 10.30.0.12

    keystone:
        build: service/keystone
        container_name: openstack-keystone
        ports:
            - 5000:5000
            - 35357:35357
        restart: always
        privileged: true
        networks:
            app_net:
                ipv4_address: 10.30.0.2

    glance:
        build: service/glance
        container_name: openstack-glance
        ports:
            - 9292:9292
        restart: always
        privileged: true
        volumes:
            - ./config/glance-api.conf:/etc/glance/glance-api.conf
            - ./volumes/image:/var/lib/glance/images
        networks:
            app_net:
                ipv4_address: 10.30.0.3

    horizon:
        build: service/horizon
        container_name: openstack-horizon
        ports:
            - 80:80
            - 443:443
        restart: always
        privileged: true
        networks:
            app_net:
                ipv4_address: 10.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.30.0.0/24
