apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-disk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: mysql:5.6
          name: database
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
          ports:
            - containerPort: 3306
              name: database
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: database-storage 
          gcePersistentDisk:
            pdName: database-disk
            fsType: ext4
