apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  ROOT_PASSWORD: password
  USER: keystone
  PASSWORD: password
  DATABASE: keystone
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 3
  secretName: my-secret
  ports:
    - containerPort: 3306
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: database-service
#spec:
#  type: NodePort
#  ports:
#    - name: public
#      port: 30001
#      targetPort: 3306
#      nodePort: 30001
#      protocol: TCP
#  selector:
#    app: my-cluster
