apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: yoneyan/openstack-glance:0.2
          ports:
            - containerPort: 9292
---
apiVersion: v1
kind: Service
metadata:
  name: glance-service
  spec:
  type: NodePort
  ports:
    - name: public
      port: 30004
      targetPort: 9292
      nodePort: 30004
      protocol: TCP
  selector:
    app: glance
