apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horizon
  template:
    metadata:
      labels:
        app: horizon
    spec:
      containers:
        - name: horizon
          image: yoneyan/openstack-horizon:0.3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: horizon-service
spec:
  type: NodePort
  ports:
    - name: public
      port: 30006
      targetPort: 80
      nodePort: 30006
      protocol: TCP
    - name: publi
      port: 30007
      targetPort: 443
      nodePort: 30007
      protocol: TCP
  selector:
    app: horizon
