apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keystone
  template:
    metadata:
      labels:
        app: keystone
    spec:
      containers:
        - name: keystone
          image: yoneyan/openstack-keystone:1.1
          ports:
            - containerPort: 5000
            - containerPort: 35357
---
apiVersion: v1
kind: Service
metadata:
  name: keystone-service
spec:
  type: NodePort
  ports:
    - name: public
      port: 30000
      targetPort: 5000
      nodePort: 30000
      protocol: TCP
  selector:
    app: keystone
