FROM centos:7

RUN yum -y install centos-release-openstack-stein epel-release
RUN sed -i -e "s/enabled=1/enabled=0/g" /etc/yum.repos.d/CentOS-OpenStack-stein.repo
RUN yum --enablerepo=centos-openstack-stein -y install openstack-glance

EXPOSE 9292


RUN systemctl enable openstack-glance-api

CMD ["/sbin/init"]
